trigger:
- main

pool:
  name: 'Default'  # Your self-hosted agent pool

variables:
  webAppName: "flask-webapp-demo1eeg4yuhghyu"
  resourceGroup: "flask-rg"

steps:
- script: python3 --version
  displayName: 'Check Python Version'
- script: |
    cd flask_app
    mv startup.txt startup.sh
    chmod +x startup.sh
  displayName: 'Prepare Startup Script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'flask_app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/flaskapp.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webAppLinux'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/flaskapp.zip'
