trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'TerraformSP'
  keyVaultName: 'terraform-kv-oro8ln'

stages:
- stage: Upload_Secrets
  displayName: 'Upload Secrets to Azure Key Vault'
  jobs:
  - job: UploadSecrets
    displayName: 'Add Secrets'
    steps:
    
    - checkout: self  # Correct way to checkout repo

    - script: echo "DB_PASSWORD=$(DB_PASSWORD)"
      displayName: 'Debug DB_PASSWORD'

    - script: echo "API_TOKEN=$(API_TOKEN)"
      displayName: 'Debug API_TOKEN'

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show

    - task: AzureCLI@2
      displayName: 'Upload Secrets to Key Vault'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az keyvault secret set --vault-name $(keyVaultName) --name "DB_PASSWORD" --value "$(DB_PASSWORD)"
          az keyvault secret set --vault-name $(keyVaultName) --name "API_TOKEN" --value "$(API_TOKEN)"
