trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TestStage
  displayName: 'Simple Test Stage'
  jobs:
  - job: EchoJob
    displayName: 'Run Echo Command'
    steps:
    - script: echo "Hello from Azure Pipeline!"
      displayName: 'Echo Hello'
