trigger:
- main

pool:
  name: 'Default'

stages:
- stage: UploadSecrets
  displayName: 'Upload Secrets to Azure Key Vault'
  jobs:
  - job: UploadSecretsJob
    displayName: 'Add Secrets'
    steps:
    - checkout: self

    - script: |
        echo "DB_PASSWORD is: $(DB_PASSWORD)"
        echo "API_TOKEN is: $(API_TOKEN)"
      displayName: 'Debug pipeline secrets'

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show

    - task: AzureCLI@2
      displayName: 'Upload Secrets to Key Vault'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az keyvault secret set --vault-name $(keyVaultName) --name db-pass --value "$(DB_PASSWORD)"
          az keyvault secret set --vault-name $(keyVaultName) --name api-token --value "$(API_TOKEN)"
