trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'TerraformSP'
  keyVaultName: 'terraform-kv-oro8ln'

stages:
- stage: UploadSecrets
  jobs:
  - job: Upload
    displayName: 'Upload Secrets to Azure Key Vault'
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: 'Upload secrets'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Setting secrets in Key Vault: $(keyVaultName)"
          az keyvault secret set --vault-name $(keyVaultName) --name DB_PASSWORD --value "$(DB_PASSWORD)"
          az keyvault secret set --vault-name $(keyVaultName) --name API_TOKEN --value "$(API_TOKEN)"
