trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'TerraformSP'  # Service connection name
  keyVaultName: 'terraform-kv-oro8ln'     # Your Azure Key Vault name

stages:
- stage: Upload_Secrets
  displayName: 'Upload Secrets to Azure Key Vault'
  jobs:
  - job: UploadSecrets
    displayName: 'Add Secrets'
    steps:
    
    # Checkout the repository first
    - task: Checkout@1
      inputs:
        fetchDepth: 1

    # Debugging step to check if the variable is set correctly
    - script: echo $(DB_PASSWORD)
      displayName: 'Debug DB_PASSWORD'
    - script: echo $(API_TOKEN)
      displayName: 'Debug API_TOKEN'

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show  # Ensures you're logged into the correct Azure account

    - task: AzureCLI@2
      displayName: 'Upload Secrets from Secure Pipeline Variables'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az keyvault secret set --vault-name $(keyVaultName) --name "DB_PASSWORD" --value "$(DB_PASSWORD)"
          az keyvault secret set --vault-name $(keyVaultName) --name "API_TOKEN" --value "$(API_TOKEN)"
