trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  TF_VAR_location: 'eastus'
  TF_VAR_environment: 'dev'
  terraformCodeDir: 'tf-az'
  app_name: 'Tf_SP'

stages:
  - stage: Validate_And_Scan
    displayName: "Validate & Scan Terraform Code"
    jobs:
      - job: validate_and_scan
        displayName: "Run Terraform Validation & Scanning"
        steps:
          - checkout: self

          - script: |
              terraform -chdir=$(terraformCodeDir) init
              terraform -chdir=$(terraformCodeDir) validate
            displayName: 'Terraform Init, Validate'
            env:
              ARM_CLIENT_ID: $(client_id)
              ARM_CLIENT_SECRET: $(client_secret)
              ARM_SUBSCRIPTION_ID: $(subscription_id)
              ARM_TENANT_ID: $(tenant_id)

  - stage: Plan
    displayName: "Terraform Plan"
    dependsOn: Validate_And_Scan
    jobs:
      - job: terraform_plan
        displayName: "Terraform Plan"
        steps:
          - checkout: self

          - script: |
              terraform -chdir=$(terraformCodeDir) init
              terraform -chdir=$(terraformCodeDir) plan \
                -var "client_id=$(client_id)" \
                -var "client_secret=$(client_secret)" \
                -var "tenant_id=$(tenant_id)" \
                -var "subscription_id=$(subscription_id)" \
                -var "app_name=$(app_name)" \
                -var "location=$(TF_VAR_location)" \
                -out=tfplan > tfplan_output.txt
              
              # Extract summary to variable
              if grep -q "No changes." tfplan_output.txt; then
                echo "##vso[task.setvariable variable=applyRequired]false"
              else
                echo "##vso[task.setvariable variable=applyRequired]true"
              fi
            displayName: 'Terraform Plan and Determine if Apply Required'
            env:
              ARM_CLIENT_ID: $(client_id)
              ARM_CLIENT_SECRET: $(client_secret)
              ARM_SUBSCRIPTION_ID: $(subscription_id)
              ARM_TENANT_ID: $(tenant_id)

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(terraformCodeDir)'
              artifactName: 'tfplan'
            displayName: 'Publish Terraform Plan Output'

  - stage: WaitForApproval
    displayName: "Wait for Manual Approval"
    dependsOn: Plan
    condition: and(succeeded(), eq(variables['applyRequired'], 'true'))  # only run if applyRequired is true
    jobs:
      - job: approval
        displayName: "Manual Approval"
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Please approve to proceed with Terraform apply'
              onTimeout: 'reject'
              timeout: '1d'

  - stage: Apply
    displayName: "Terraform Apply"
    dependsOn: WaitForApproval
    condition: and(succeeded(), eq(variables['applyRequired'], 'true'))
    jobs:
      - job: terraform_apply
        displayName: "Terraform Apply"
        steps:
          - checkout: self

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'tfplan'
              path: '$(terraformCodeDir)'

          - script: |
              terraform -chdir=$(terraformCodeDir) init
              terraform -chdir=$(terraformCodeDir) apply tfplan
            displayName: 'Terraform Apply'
            env:
              ARM_CLIENT_ID: $(client_id)
              ARM_CLIENT_SECRET: $(client_secret)
              ARM_SUBSCRIPTION_ID: $(subscription_id)
              ARM_TENANT_ID: $(tenant_id)
